name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v2

      - name: Run install
        run: npm install

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
